# This file was generated by GoReleaser. DO NOT EDIT.
cask "keycard" do
  name "keycard"
  desc "Delightful credential management for developers, services and agents"
  homepage "https://keycard.ai"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keycard"

  on_macos do
    on_intel do
      url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_MacOS_x86_64.zip",
        verified: "github.com/keycardai/homebrew-tap/"
      sha256 "b50e0f679605813e2aa7b8979b1832999a3a32c9f912a83462c7dbcdfa3c1630"
    end
    on_arm do
      url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_MacOS_arm64.zip",
        verified: "github.com/keycardai/homebrew-tap/"
      sha256 "99f62333d221716733a6015dfb123d6a8bd1189ffd8c7676e27866cb77cd064b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_Linux_x86_64.tar.gz",
        verified: "github.com/keycardai/homebrew-tap/"
      sha256 "f34f789cf23ba48204e8dd3312a9c1724e6954c288c1dd137d12253898363da2"
    end
    on_arm do
      url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_Linux_arm64.tar.gz",
        verified: "github.com/keycardai/homebrew-tap/"
      sha256 "a868f1233d58d7cabe35025b48c91f8c72b3b6e1d4fb6a37e6ce5920d7bb46d3"
    end
  end

  postflight do
    if (claude_path = which("claude"))
      system_command claude_path, args: ["plugin", "marketplace", "add", "keycardai/plugins"], must_succeed: false
      system_command claude_path, args: ["plugin", "install", "cli@keycard"], must_succeed: false
    end
  end

  uninstall_preflight do
    if (claude_path = which("claude"))
      system_command claude_path, args: ["plugin", "uninstall", "cli@keycard"], must_succeed: false
    end
  end

  # No zap stanza required
end
