# This file was generated by GoReleaser. DO NOT EDIT.
cask "keycard" do
  version "0.0.27"

  on_macos do
    sha256 "9240f53545e957a4d837d41dbe7e32af42c6cb76305ab915a46643856c628b56"
    url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_MacOS_all.zip",
        verified: "github.com/keycardai/homebrew-tap/"
  end

  on_linux do
    on_intel do
      sha256 "e10febdd3232773e754ca63ba9848a02d6f0a9649d9efa4f72c2e46cef76f10a"
      url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_Linux_x86_64.tar.gz",
        verified: "github.com/keycardai/homebrew-tap/"
    end
    on_arm do
      sha256 "69327aac2012213d9407da913cb350df19102e0f83e4e10f60db23dd0ca7eaff"
      url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_Linux_arm64.tar.gz",
        verified: "github.com/keycardai/homebrew-tap/"
    end
  end

  name "keycard"
  desc "Delightful credential management for developers, services and agents"
  homepage "https://keycard.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keycard"

  postflight do
    ENV["PATH"] = ["#{Dir.home}/.claude/local", "#{Dir.home}/.local/bin", "#{HOMEBREW_PREFIX}/bin", ENV["PATH"]].join(":")
    if (claude_path = which("claude"))
      list_result = system_command(claude_path.to_s, args: ["plugin", "list"], must_succeed: false)
      plugin_section = list_result.stdout[/keycard-cli@keycardai[\s\S]*?(?=\n\s+❯|\z)/]
      if plugin_section.nil?
        puts "To install the Keycard Claude Code plugin, run:"
        puts "  claude plugin marketplace add keycardai/plugins && claude plugin install keycard-cli@keycardai"
      elsif !plugin_section.include?("Version: #{version}")
        puts "To update the Keycard Claude Code plugin to #{version}, run:"
        puts "  claude plugin update keycard-cli@keycardai"
      end
    else
      puts "To install the Keycard Claude Code plugin, once Claude Code is available, run:"
      puts "  claude plugin marketplace add keycardai/plugins && claude plugin install keycard-cli@keycardai"
    end
  end

  uninstall_preflight do
    unless ENV["HOMEBREW_UPGRADE_FROM_VERSION"]
      ENV["PATH"] = ["#{Dir.home}/.claude/local", "#{Dir.home}/.local/bin", "#{HOMEBREW_PREFIX}/bin", ENV["PATH"]].join(":")
      if (claude_path = which("claude"))
        system_command claude_path.to_s, args: ["plugin", "uninstall", "keycard-cli@keycardai"], must_succeed: false
      end
    end
  end

  # No zap stanza required

end
