# This file was generated by GoReleaser. DO NOT EDIT.
cask "keycard" do
  version "0.0.24"

  on_macos do
    sha256 "bca1a3cf26cac3396a2433f59c27051c48d61dc21b887ab5558db08ed44efde6"
    url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_MacOS_all.zip",
        verified: "github.com/keycardai/homebrew-tap/"
  end

  on_linux do
    on_intel do
      sha256 "d6f4decd7ea899c6917e0ee51f026f77abcbde007945f0554f4d7921192a7b03"
      url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_Linux_x86_64.tar.gz",
        verified: "github.com/keycardai/homebrew-tap/"
    end
    on_arm do
      sha256 "39a1d7f3315f81a62fffbbe2dc492cf61de597f79fcb5b78a50e524b3be9f744"
      url "https://github.com/keycardai/homebrew-tap/releases/download/v#{version}/keycard_Linux_arm64.tar.gz",
        verified: "github.com/keycardai/homebrew-tap/"
    end
  end

  name "keycard"
  desc "Delightful credential management for developers, services and agents"
  homepage "https://keycard.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keycard"

  postflight do
    ENV["PATH"] = ["#{Dir.home}/.claude/local", "#{Dir.home}/.local/bin", "#{HOMEBREW_PREFIX}/bin", ENV["PATH"]].join(":")
    if (claude_path = which("claude"))
      list_result = system_command(claude_path.to_s, args: ["plugin", "list"], must_succeed: false)
      plugin_section = list_result.stdout[/keycard-cli@keycardai[\s\S]*?(?=\n\s+❯|\z)/]
      if plugin_section.nil?
        puts "To install the Keycard Claude Code plugin, run:"
        puts "  claude plugin marketplace add keycardai/plugins && claude plugin install keycard-cli@keycardai"
      elsif !plugin_section.include?("Version: #{version}")
        puts "To update the Keycard Claude Code plugin to #{version}, run:"
        puts "  claude plugin update keycard-cli@keycardai"
      end
    else
      puts "To install the Keycard Claude Code plugin, once Claude Code is available, run:"
      puts "  claude plugin marketplace add keycardai/plugins && claude plugin install keycard-cli@keycardai"
    end
  end

  uninstall_preflight do
    unless ENV["HOMEBREW_UPGRADE_FROM_VERSION"]
      ENV["PATH"] = ["#{Dir.home}/.claude/local", "#{Dir.home}/.local/bin", "#{HOMEBREW_PREFIX}/bin", ENV["PATH"]].join(":")
      if (claude_path = which("claude"))
        system_command claude_path.to_s, args: ["plugin", "uninstall", "keycard-cli@keycardai"], must_succeed: false
      end
    end
  end

  # No zap stanza required

end
